#!/bin/bash
################################################
# preinst script main
################################################
sbindir=/sbin
sysconfdir=/etc
unitdir=$(sysconfdir)/systemd/system

UNIT = usb-gadget.service

SCRIPTS = \
	configure-gadget.sh \
	remove-gadget.sh

case "$1" in
	install)
		crontab -r
		rm /etc/init.d/adbd.sh
		mkdir -p $(sysconfdir)/gadget
		mkdir -p $(sbindir)
		for s in $(SCRIPTS); do \
			install -m 755 $$s $(sbindir)/$${s%.sh}; \
		done
		mkdir -p $(unitdir)
		install -m 600 $(UNIT) $(unitdir);
		systemctl daemon-reload
		systemctl enable usb-gadget.service
		echo "USB Gadget awake after reboot"
		
	;;
	upgrade)
		
	;;
	*)
	;;
esac
