#!/bin/bash
################################################
# preinst script main
################################################
sbindir=/sbin
sysconfdir=/etc
unitdir=$(sysconfdir)/systemd/system

UNITS = \
	usb-gadget.service \
	checkOTG.service

SCRIPTS = \
	configure-gadget.sh \
	remove-gadget.sh \
	check-gadget.sh

case "$1" in
	install)
		crontab -r
		rm /etc/init.d/adbd.sh
		mkdir -p $(sysconfdir)/gadget
		mkdir -p $(sbindir)
		for s in $(SCRIPTS); do \
			install -m 755 $$s $(sbindir)/$${s%.sh}; \
		done
		mkdir -p $(unitdir)
		for u in $(UNITS); do \
			install -m 600 $$u $(DESTDIR)$(unitdir); \
		done
		systemctl daemon-reload
		systemctl enable usb-gadget.service
		systemctl enable checkOTG.service
		echo "USB Gadget awake after reboot"
		
	;;
	upgrade)
		
	;;
	*)
	;;
esac
